services:
  mssql:
    container_name: mssql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abcDEF123#
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    working_dir: /src
    ports:
      - 1433:1433
    volumes: 
      - ./sql:/sql